global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user-api:8080"]

  - job_name: "product-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["product-api:8080"]

  - job_name: "notification-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-api:8080"]

  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]
